[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "zrs"
version = "0.1.0"

[dependencies]
dirs = "1"
regex = "1"
tempfile = "3"
nix = "0.11"

[dependencies.clap]
default-features = false
version = "2"

[dependencies.failure]
default-features = false
version = "0.1"

[profile.release]
lto = true
