[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "zrs"
version = "0.1.7"

description = "Jump to recently used directories"
repository = "https://github.com/FauxFaux/zrs"
readme = "README.md"

categories = ["command-line-utilities", "development-tools"]
license = "MIT OR Apache-2.0"

edition = "2018"

[dependencies]
dirs = "2"
regex = "1"
tempfile = "3"
twoway = "0.2"
nix = "0.17"

[dependencies.clap]
default-features = false
version = "2"

[dependencies.failure]
default-features = false
features = ["std"]
version = "0.1"

[profile.release]
lto = true
